### ISSUE TITLE
HotAC on TTS

### ISSUE THREAD

**Issue by Medley475** [rune-b/hotac-index#2]
There are two new Workshops on Tabletop Simulator for HotAC. One is unified and the other is a french version. Both use the X-Wing 2.0 Unified workshop as their base.

**Comment by rune-b** [comment]
Hi. I don't use TTS myself. Do you have links?

**Comment by Medley475** [comment]
Steam Workshop::X-Wing 2.0 Unified HotAC

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Steam Workshop::X-Wing 2.0 Unified HotAC


 |

 |

 |

Steam Workshop::X-wing Unified 2.0 campagne FR

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Steam Workshop::X-wing Unified 2.0 campagne FR


 |

 |

 |






    On Sunday, October 11, 2020, 1:20:27 PM EDT, rune-b <notifications@github.com> wrote:  
 
 


Hi. I don't use TTS myself. Do you have links?

**Comment by rune-b** [comment]
Thanks. I have added these links and some more TTS workshops I found

**Comment by Medley475** [comment]
Not at my computer atm, but do you have the Discord Channel as link?
Jim

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 12, 2020 at 10:25 AM, rune-b<notifications@github.com> wrote:   


Closed #2.

**Comment by rune-b** [comment]
No
Is there a HotAC discord channel?

**Comment by Medley475** [comment]
yes,
Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!

Check out the HotAC Custom Campaigns, Missions, & Rules community on Discord - hang out with 117 other members a...
 |

 |

 |

is a temp invite. you will need to contact the moderator for a permanent link



s

    On Monday, October 12, 2020, 1:10:07 PM EDT, rune-b <notifications@github.com> wrote:  
 
 


No
Is there a HotAC discord channel?

**Comment by rune-b** [comment]
Do you have a link to it?

**Comment by Medley475** [comment]
Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!

Check out the HotAC Custom Campaigns, Missions, & Rules community on Discord - hang out with 117 other members a...
 |

 |

 |




    On Tuesday, October 13, 2020, 2:30:32 AM EDT, rune-b <notifications@github.com> wrote:  
 
 


Do you have a link to it?

**Comment by rune-b** [comment]
I just get the text "Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!", no actual link

**Comment by Medley475** [comment]
hmm, it shows up as a blue link when I post it

    On Tuesday, October 13, 2020, 2:35:54 AM EDT, rune-b <notifications@github.com> wrote:  
 
 


I just get the text "Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!", no actual link

**Comment by Medley475** [comment]
https://discord.com/invite/GSXndQr




    On Tuesday, October 13, 2020, 2:35:54 AM EDT, rune-b <notifications@github.com> wrote:  
 
 


I just get the text "Join the HotAC Custom Campaigns, Missions, & Rules Discord Server!", no actual link

**Comment by rune-b** [comment]
thanks

**Comment by rune-b** [comment]
Discord server is now finally added. I also joined it myself, though it doesn't seem to be very active
